"""empty message

Revision ID: 381b354b4d0e
Revises: e71da4861fec
Create Date: 2024-10-22 15:42:58.886616

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '381b354b4d0e'
down_revision = 'e71da4861fec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bets', 'user_id')
    # ### end Alembic commands ###
