"""empty message

Revision ID: 3889e3a4becd
Revises: 381b354b4d0e
Create Date: 2024-10-23 08:04:38.628512

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '3889e3a4becd'
down_revision = '381b354b4d0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bets_event_uuid_key', 'bets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bets_event_uuid_key', 'bets', ['event_uuid'])
    # ### end Alembic commands ###
